import { defineConfig } from "tsdown";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  clean: true,
  dts: true,
  hash: false,
  external: [
    "vite",
    "webpack",
    "rollup",
    "esbuild",
    "rspack",
    "unplugin",
    "fs",
    "path",
    "http",
    "crypto",
    "url",
    // Optional dependencies for @vue/compiler-sfc
    "pug",
    "hogan.js",
    "templayed",
    "handlebars",
    "underscore",
    "walrus",
    "mustache",
    "just",
    "dustjs-linkedin",
    "slm",
    "coffee-script",
    "marko",
    "squirrelly",
    "twing",
    "teacup/lib/express",
    "react",
    "react-dom",
    "vue",
    "@vue/compiler-sfc",
    "@vue/compiler-core",
    "@vue/shared",
  ],
  noExternal: ["@mcpc-tech/cmcp"],
  define: {
    "process.env.NODE_ENV": '"production"',
  },
});
